name: Загрузка артефакта

on: [push]

jobs:
  upload_artifact:
    name: Создание и загрузка нового атефакта
    runs-on: ubuntu-latest

    env:
      ALL_REQUIREMENTS_FILE: List of all requirements.txt

    steps:
      - uses: actions/checkout@v2 # Склонировать содержимое репозитория

      - name: Создание артефакта
        run: |
          cat requirements.txt > ./all_reqs.txt
          cat requirements.dev.txt >> ./all_reqs.txt

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ALL_REQUIREMENTS_FILE }}
          path: ./all_reqs.txt
